/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AiDesignRouteImport } from './routes/ai-design'
import { Route as IndexRouteImport } from './routes/index'

const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDesignRoute = AiDesignRouteImport.update({
  id: '/ai-design',
  path: '/ai-design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-design': typeof AiDesignRoute
  '/builder': typeof BuilderRoute
  '/cart': typeof CartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-design': typeof AiDesignRoute
  '/builder': typeof BuilderRoute
  '/cart': typeof CartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-design': typeof AiDesignRoute
  '/builder': typeof BuilderRoute
  '/cart': typeof CartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-design' | '/builder' | '/cart'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-design' | '/builder' | '/cart'
  id: '__root__' | '/' | '/ai-design' | '/builder' | '/cart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDesignRoute: typeof AiDesignRoute
  BuilderRoute: typeof BuilderRoute
  CartRoute: typeof CartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-design': {
      id: '/ai-design'
      path: '/ai-design'
      fullPath: '/ai-design'
      preLoaderRoute: typeof AiDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDesignRoute: AiDesignRoute,
  BuilderRoute: BuilderRoute,
  CartRoute: CartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
